### PR TITLE
Update source formatting for Podfile.

### PR DESCRIPTION
**Pull request by shepting**
This will update the `Podfile` example to show syntax highlighting. Also matches up the indentation.

Also, great job open-sourcing!

### CODE REVIEW

**Comment by katejlee** [comment]
Thanks for the contribution, but to merge your change, github requires you to sign CLA :) Once that's done, we'll merge the change!

**Comment by shepting** [comment]
Finally signed the Code of Conduct.

**Comment by shepting** [comment]
@andypiper @katejlee Want to merge this?

**Comment by katejlee** [comment]
This got pulled into the internal repository. It will be included in coming release.

**Pull request closed without merging**
